name: Continuous Integration Checks

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go v1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check Formatting
        run: test -z $(gofmt -l .)
      - name: Run Tests
        run: go test ./...
